### PR TITLE
Project 1 Layout Polina

### PR DESCRIPTION
**Pull request by polinamials**
Github keeps saying there is an error in my layout???

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (605.0, 410.07) is larger than the maximum size of 605.0 X 410.0 microns

**Comment by polinamials** [comment]
I fixed this error in the file in the branch polinamials-layout3, but the verification still gives me these errors: 

image

Do you know how to fix this?

**Comment by lukasc-ubc** [comment]
Hi Polina,
I made changes to the verification scripts.  See if you have a "Sync Fork" button in your Fork. Then run again.
Or just make a pull request, and it will run on the main branch.
image

**Comment by polinamials** [comment]
It works now, thank you so much!

**Pull request closed without merging**
