### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by agafonov1**

### CODE REVIEW

**Comment by agafonov1** [comment]
draft submission

**Comment by lukasc-ubc** [comment]
Can you please verify your layout?  There are disconnected grating couplers, which you can delete.
thank you

**Comment by lukasc-ubc** [comment]
Also:
Turn on the GitHub Actions on your forked repository (In your repository's page on GitHub, click on Actions in the top-menu bar, and Enable the workflows).

**Comment by lukasc-ubc** [comment]
@agafonov1 how is it going?

**Pull request closed without merging**
