### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rmicanek**
Increased grating coupler clearances
Renamed devices to avoid conflicts
Pin errors should not cause fab issues

### CODE REVIEW

**Comment by omidesml** [comment]
What's the difference between A vs AA, B vs BB, etc? They seem identical.

**Comment by rmicanek** [comment]
They are. I wanted to compare pairs of devices. On Feb 10, 2024, at 11:09 PM, omidesml ***@***.***> wrote:﻿
What's the difference between A vs AA, B vs BB, etc? They seem identical.

**Comment by omidesml** [comment]
@rmicanek  Please check the Functional Verifications. I checked the design D and there are some misalignments between the waveguides. 

Regarding identical designs: @lukasc-ubc each design comes with an identical copy. I'm not sure if the measurement results would be conclusive to show variations by copying the designs. Please let me know your feedback.

**Comment by omidesml** [comment]
Are these intentional? 
image

**Comment by rmicanek** [comment]
No. Resubmitted. On Feb 11, 2024, at 1:42 PM, omidesml ***@***.***> wrote:﻿
Are these intentional?
image.png (view on web)

**Comment by rmicanek** [comment]
I don’t see my latest files in the ‘latest merge’ link. They are my old ones. Does the merge link get updated automatically or can it be outdated?On Feb 11, 2024, at 11:17 PM, Lukas Chrostowski ***@***.***> wrote:﻿
Merged #283 into main.

**Pull request merged**
