### PR TITLE
devenchack files upload pull request

### PR DESCRIPTION
**Pull request by Rajarshi1505**

### CODE REVIEW

**Comment by Rajarshi1505** [comment]
added files and merged

**Comment by lukasc-ubc** [comment]
@Rajarshi1505 can you fix the error? thank you.

**Comment by Rajarshi1505** [comment]
uploaded files for devenchack

**Comment by lukasc-ubc** [comment]
you have some rather severe stair-casing effects in your waveguide. is that intentional?

image

**Comment by Rajarshi1505** [comment]
Yes, those are gratings

**Comment by Rajarshi1505** [comment]
I did merge shapes along with the gratings and waveguides

**Comment by Rajarshi1505** [comment]
The stairs casing also might have been caused due to direct refractive
index contour export from lumerical refractive index monitor

**Pull request merged**
