### PR TITLE
research project, maybe elec582

### PR DESCRIPTION
**Pull request by DantePrins**
I was told there was lots of room, if not prioritize Rings, DifRings1A, DifRings2A

### CODE REVIEW

**Comment by DantePrins** [comment]
these overlap errors are not an issue, please accept.

**Comment by lukasc-ubc** [comment]
make sure all the files are in the submissions folder.

**Comment by lukasc-ubc** [comment]
please put the files in the correct place.

image

**Comment by DantePrins** [comment]
should be fixed

**Pull request merged**
