### PR TITLE
Merge in Joels changes

### PR DESCRIPTION
**Pull request by Tsuchijo**

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
@Tsuchijo Can you please fix the errors?

**Comment by lukasc-ubc** [comment]
it is the floorplan box that is incorrect.

**Comment by lukasc-ubc** [comment]
for some reason, your files are being deleted. can you see if. you can fix this pull request?
also not sure why the python file is not working.
image

**Comment by Tsuchijo** [comment]
sorry I was a few things with different files because I wasn't sure what was causing it to fail the checks. Ill close and reopen the pull request to keep things clean The python appears to be failing because its looking for the file in the wrong directory? it seems to be looking in the root directory instead of the submissions folder.

**Pull request closed without merging**
