### PR TITLE
testing layout

### PR DESCRIPTION
**Pull request by AndreyUBC**
for the test

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
@AndreyUBC All of your opt_in labels are identical, please make them unique.

**Comment by lukasc-ubc** [comment]
Errors detected: merge/EBeam.oas, 1 errors. ELEC413_Andrey_P1.gds, 16 errors. 

please remove the merge/EBeam files.

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (614.0, 410.0) is larger than the maximum size of 605.0 X 410.0 microns

**Comment by AndreyUBC** [comment]
Hey Lucas, I think that was my last testing Layout. How can I start from the beggining and submit completely new layout? I can not just upload it for some reason, even though i tried to do something in "Action" page but no results. I read the submission instruction, but still cant figure it out

**Comment by lukasc-ubc** [comment]
Please only commit the files that are part of your submission, i.e., submissions/*.gds

I will close this PR and you can start again, hopefully with only your three ELEC413*.gds files.

image

**Pull request closed without merging**
