### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sfwise**

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
@sfwise Can you fix this?
image

**Comment by sfwise** [comment]
I think I uploaded the wrong version of my layout, that shouldn’t be there
I’ll go take a look.

**Comment by sfwise** [comment]
Hi I have added a new submission, I have never used GitHub so I am unsure
if I have created the pull request correctly. The final file should just be
EBeam_sfwise.gds and has the comment ' this is my final design'

**Comment by sfwise** [comment]
Hi
I noticed on the newest merge file both of my layouts are there. The top
one on the left shown in the image with only 7 devices shouldn't be there.
The one below which is the EBeam_sarahfwise.gds should be my only design
(the one highlighted in the cell selection window and shown in the image
with 8 devices). The EBeam_sarahfwise_v5.gds was an error as I uploaded the
incomplete file.
 [image: image.png]

**Pull request merged**
