### PR TITLE
Create Ebeam_masihb.gds

### PR DESCRIPTION
**Pull request by masihUBC**
version1

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
@masihUBC Can you please fix the errors?

**Comment by omidesml** [comment]
@lukasc-ubc Flagging this bug here. Masih's ELEC413 design is error free (downloaded the layout and checked on my laptop) but the verification action fails here.

**Comment by Hang-Bobby-Zou** [comment]
@omidesml It seems that there are some issues with the auto merge if you look at the merged floor plan. Any idea what could cause that?

**Comment by lukasc-ubc** [comment]
This needs to be rejected, since there are more than 1 top cells.

image

@masihUBC please fix and resubmit.

**Pull request merged**
