### PR TITLE
Masih-lens design project

### PR DESCRIPTION
**Pull request by masihUBC**
Hi Lukas, 
I added 3 stacks of the circuit for more de-risking purposes. 
I could not make the circuit in smaller versions as you asked mainly because of the loopback needed for the isolator idea (more than 1mm of loopback needed which cannot fit in smaller areas). I talked to Matthew and he said we might be able to do post process and remove the oxide that is why I kept the oxide open layer as he suggested. 
can you please manually put this on the edge of the chip so the right side of the chip is on the edge? 
Thanks 
Masih

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
@masihUBC Your design does not follow the floor plan area and thus cannot be merged automatically. I have also noticed that you have some edge couplers that are not exactly on the edge. Can you please specify.

@lukasc-ubc This may need to do a manual merge for Masih's design

**Comment by lukasc-ubc** [comment]
@masihUBC we are doing a last-minute run with ANT where there is no oxide.  Only air.  Would your isolator design be more suitable for that?
we are submitting on Monday.

If so, can you split it up, to have lenses on the regular ANT run, and isolators on another one?  I'll provide you the repo info for the other one.

**Comment by lukasc-ubc** [comment]
@masihUBC 
if you want to include these designs on the edX chip, please rotate the GCs, and break up your design into multiple files as per the area requirement.  We will not be post-process etching the edX chip.

**Comment by masihUBC** [comment]
Yes, Lukas sorry I was in the airplane and transit on Sunday 
Just arrived in Toronto.
Please provide me the repo for the other one (air only).
I'll update my design for the current run (oxide) as well with GC only in the assigned floorplan. I can do it all in the next 4 hours 
Thanks 
Masih

**Pull request closed without merging**
