### PR TITLE
Nick's design

### PR DESCRIPTION
**Pull request by N1ckL3**

### CODE REVIEW

**Comment by Hang-Bobby-Zou** [comment]
Hi @N1ckL3 Can you please move your file into the "/submissions/" folder?

**Comment by N1ckL3** [comment]
Could you tell me how to move the file?

**Comment by N1ckL3** [comment]
> Hi @N1ckL3 Can you please move your file into the "/submissions/" folder?


Could you tell me how to move the file?

**Comment by Hang-Bobby-Zou** [comment]
Hi @N1ckL3 The best way is to close this PR and make a new PR with the file in correct location. Can you try to do that?

**Comment by N1ckL3** [comment]
> Hi @N1ckL3 The best way is to close this PR and make a new PR with the file in correct location. Can you try to do that?

Ok thanks

**Pull request closed without merging**
