### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cpapakonstantinou**
grating antenna design variations

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
You will be purchasing the SEM images?

**Comment by lukasc-ubc** [comment]
Also, what angle of emission do you expect from the antenna?  Our fibers are 8º polish, i.e., 12º injection angle.

**Comment by cpapakonstantinou** [comment]
I did not realize SEM  imaging was at additional cost. it is better I remove the SEM blocks from the layout. If I wanted to retain an image, is payment invoiced to my CMC account?

The designs were optimized for vertical. The scattering matrix for most look ok with 12deg injection. I'm interested  in the bandwidth.

**Comment by lukasc-ubc** [comment]
The SEM cost is separate

**Pull request merged**
